### ISSUE TITLE
Huge CPU usage generated by BlockBlock - conflict or interaction ?

### ISSUE THREAD

**Issue by luckman212** [objective-see/BlockBlock#10]
- BlockBlock 1.0.2
- macOS 10.15.5

I don't know how to track this down, but another app on my system: [BackupLoupe](https://www.soma-zone.com/BackupLoupe/) (which offers advanced functions for working with Time Machine backups) causes very high CPU usage from BlockBlock while it's indexing TimeMachine data.

I submitted a report to the developer of BackupLoupe already, but I also wanted to post some detail here in case the issue turns out to be with BlockBlock instead. BackupLoupe spawns a subprocess that does the indexing, called `com.soma-zone.BackupLoupe.Scanner` - this may be a LaunchDaemon (?) which is why I assume BlockBlock is getting "involved". But no alerts or anything pop up from BlockBlock, just seeing high CPU spikes during the scans, to the point that the scans are not able to complete their work.

I dumped out 2 "samples" from Activity monitor (attached) - and some screenshots are posted below. Not sure what else can be done to track down this problem.

[Sample of BlockBlock.txt](https://github.com/objective-see/BlockBlock/files/4635160/Sample.of.BlockBlock.txt)
[Sample of com.soma-zone.BackupLoupe.Scanner.txt](https://github.com/objective-see/BlockBlock/files/4635162/Sample.of.com.soma-zone.BackupLoupe.Scanner.txt)

![image](https://user-images.githubusercontent.com/1992842/82066026-e3416600-969c-11ea-8347-d0cc639972cb.png)

![image](https://user-images.githubusercontent.com/1992842/82065940-bb520280-969c-11ea-8db2-e854f256d985.png)

**Comment by luckman212** [comment]
@objective-see Came back to post an update: Today I noticed that in fact _any_ heavy network traffic stream seems to trigger this high CPU usage in BlockBlock. Even a simple `curl some-large-file.dmg` will cause CPU usage to near 100%:
![image](https://user-images.githubusercontent.com/1992842/84734349-a48a1e80-af6e-11ea-84b0-7ef731befccc.png)
![image](https://user-images.githubusercontent.com/1992842/84734474-ec10aa80-af6e-11ea-8c2c-8f93ed2f57b5.png)
I had a bleary-eyed look through the source code to see if I could find any reason for this and (surprise) I couldn't. I'm guessing that somehow just invoking the Endpoint Security Framework automatically enables **ALL** of the monitoring/logging that goes along with that (file, process, socket, etc) even though BlockBlock is only alerting against file activity. Is this reasonable to assume?

For now I had to disable BB, but I hope maybe a solution can be found.

**Comment by tiennou** [comment]
I'm seeing the same thing, while running Xcode (I think), consistent 90+% CPU usage. Here's a few captured stack traces in case this helps…
[BlockBlock-2.txt](https://github.com/objective-see/BlockBlock/files/6442690/BlockBlock-2.txt)
[BlockBlock.txt](https://github.com/objective-see/BlockBlock/files/6442693/BlockBlock.txt)

**Comment by kswope** [comment]
I'm seeing this problem when benchmarking backend APIs.  When I originally ran blockblock a few years ago I don't think I had this problem, so maybe its a change in OSX or blockblock itself.

Here's the issue
https://github.com/kemalcr/kemal/issues/625

**Comment by kswope** [comment]
Found a simple confirmation of the problem.  Compiling a simple "hello world" golang program, which is usually instant on my MBA M1, takes about 4 seconds when BlockBlock is enabled in the menu.  If I repeadedly repeat the compilation.

Running the compilation in a loop like this

```
watch -n0 go run main.go
```

spikes and holds BlockBlock at about 20% CPU

**Comment by GeorgFleig** [comment]
I noticed heavy impact on some operations on my M2 Macbook Pro running MacOS Sonoma 14.3.1.
Especially some docker/rosetta related commands become a lot slower. Getting the ssh configuration of a vagrant Docker machine (`vagrant ssh-config`).

- BlockBlock disabled: `vagrant ssh-config  0.65s user 0.23s system 95% cpu 0.929 total`
- BlockBlock enabled: `vagrant ssh-config  1.07s user 0.43s system 6% cpu 24.415 total`

While executing this command, I watched BlockBlock in the activity monitor. It reads about 750MB of data during this 24s execution time. Something is clearly broken.. Happy to provide more details/debug information, if you let me know what is needed.

**Comment by rgrove** [comment]
I'm experiencing this issue when BlockBlock is enabled on a system that's running [Jamf Protect](https://www.jamf.com/products/jamf-protect/).

I put together [a simple Node.js-based benchmark](https://github.com/rgrove/jamf-node-fork-performance) that demonstrates the problem by forking 50 worker processes. With BlockBlock and Jamf Protect both enabled, this benchmark takes over 100x longer to finish than it does when either BlockBlock _or_ Jamf Protect is disabled.

**Comment by objective-see** [comment]
Thanks for the feedback on this!  Looking into performance issues first in BlockBlock, then once those have been addressed will sync with the Jamf team. 

Stress testing BB (and the stack traces, thanks for those @tiennou) has revealed, yes, a significant performance issue if "Notarization Mode" is enabled:
<img width="587" alt="image" src="https://github.com/user-attachments/assets/787f3b66-c039-46cc-8a5b-85461e652af8">

However if this preference is turned off, even while BB is still running, runtimes of the stress tests (such as compiling large projects) appear not to be significantly impacted. (Not saying there aren't other performance issues, but this is a clear one that has been identified, that I'm prioritizing it a fix). In the meantime can you turn off "Notarization Mode" and let me know if that alleviates the issue? (If not, or if it was never on, please let me know too!).

Mahalo for your reports and patience 🙏🏽

**Comment by rgrove** [comment]
@objective-see Thanks for taking a look!

I use BlockBlock with Notarization Mode off, but I went ahead and tested this anyway just to see if it made a difference.

With Jamf Protect enabled, I ran my [process forking benchmark](https://github.com/rgrove/jamf-node-fork-performance) first with Notarization Mode off, then with Notarization Mode on, and saw no difference in performance. Both took ~32 seconds to finish. With BlockBlock fully disabled, the benchmark consistently finishes in less than 1 second.

Here's a video demonstrating this in real-time along with `top` output so you can see what's consuming CPU time: https://drive.google.com/file/d/1xwLauGpzcvCzze11P1BDkNxBWqr4Z_Z7/view

**Comment by objective-see** [comment]
I've just published a [new release (v2.2.3)](https://github.com/objective-see/BlockBlock/releases/tag/v2.2.3) with a myriad of performance improvements ...both for notarization mode, but also more generally for situations where a lot of processes are rapidly created (e.g. building/making). 

I've tested to ensure that there is no massive BlockBlock CPU spikes and/or time difference (when compared to BlockBlock being disabled) in the following scenarios mentioned in this issue including:

1. Downloading a large file 
(e.g. curl some-large-file.dmg)

2. Building a Go binary over and over
(as noted by @kswope)
![image](https://github.com/user-attachments/assets/9d8097a8-85f5-40d6-81d0-0eaa342e072d)

3. Process forking
(as noted by @rgrove's in his [process forking benchmark](https://github.com/rgrove/jamf-node-fork-performance))
<img width="1006" alt="image" src="https://github.com/user-attachments/assets/ef521b11-9392-4e70-9b3a-199d348b9aa1">

If you have to the time to also test, and let know if the performance (or any other) issues persist, that'd be super helpful 🙏🏽

**Comment by objective-see** [comment]
> @objective-see Thanks for taking a look!
> 
> I use BlockBlock with Notarization Mode off, but I went ahead and tested this anyway just to see if it made a difference.
> 
> With Jamf Protect and BlockBlock enabled, I ran my [process forking benchmark](https://github.com/rgrove/jamf-node-fork-performance) first with Notarization Mode off, then with Notarization Mode on, and saw no difference in performance. Both took ~32 seconds to finish. With BlockBlock fully disabled, the benchmark consistently finishes in less than 1 second.
> 
> Here's a video demonstrating this in real-time along with `top` output so you can see what's consuming CPU time: https://drive.google.com/file/d/1xwLauGpzcvCzze11P1BDkNxBWqr4Z_Z7/view

Thank you for reporting the issue and even more so, for the performance test! 

Unfortunately I don't have Jamf Protect installed, but if it's the one with the CPU spiking, IMHO it seems that to point to an issue with them (albeit yes, triggered by BlockBlock)?

On my box, with this latest version of BlockBlock, there was no noticeably difference between having BlockBlock enabled or disabled when running (and re-running) the test ....it always took around 400ms to complete  🤷🏻‍♂️

Any other ideas? I can definitely reach out to the Jamf folks too?

**Comment by rgrove** [comment]
@objective-see 
> Unfortunately I don't have Jamf Protect installed, but if it's the one with the CPU spiking, IMHO it seems that to point to an issue with them (albeit yes, triggered by BlockBlock)?

Agreed; the process forking performance issue demonstrated by my test case seems to be an interaction specifically between Jamf Protect and BlockBlock. With either one disabled, I don't see a performance problem. But with both of them enabled, process forking seems to cause Jamf Protect to consume excessive CPU, and performance takes a nosedive.

I re-tested with BlockBlock 2.2.3 just now and unfortunately there's no improvement; when both Jamf Protect and BlockBlock are enabled, the test still finishes in ~32 seconds, same as with 2.2.2.

> Any other ideas? I can definitely reach out to the Jamf folks too?

If you have contacts there, that might be helpful! Before we discovered the BlockBlock connection, we spent a lot of time trying to get help via Jamf's normal support channels and didn't get anywhere. I'm willing to try again with this new information, but you might have better luck if you know someone there.

**Comment by objective-see** [comment]
@rgrove, thanks for the additional information! 
Have pinged the team lead & devs of Jamf Protect so hopefully we'll get this shorted out soon(ish)! 🤞🏽

**Comment by objective-see** [comment]
@rgrove, while the Jamf folks are digging into this as well, can you try a few other things to help collect more data to help get this tracked down/fixed? 🙏🏽

1. Can you test Jamf Protect + [ProcessMonitor](https://objective-see.org/products/utilities.html#ProcessMonitor) and/or [FileMonitor](https://objective-see.org/products/utilities.html#FileMonitor)?  I'm wanting to see if its something specific to BlockBlock, or if its simple the running of 2x Endpoint Security clients

2. While Jamf Protect is pegging the CPU, can you sample it? This will show the stack backtraces where it's spending all its time. (You can do this via Activity Monitor, or from the Terminal as well). If you can post the sample here, that'd be great!

**Comment by rgrove** [comment]
@objective-see With Jamf Protect enabled, neither ProcessMonitor nor FileMonitor (nor even running both at the same time) has an appreciable effect on the runtime of the fork test or on the CPU usage of the Jamf Protect process.

Here's a Jamf Protect sample taken while running the fork test with BlockBlock enabled. Hope it helps! 

[Sample of com.jamf.protect.security-extension.txt](https://github.com/user-attachments/files/16982920/Sample.of.com.jamf.protect.security-extension.txt)

**Comment by objective-see** [comment]
Thanks @rgrove! Super helpful ...and with your feedback + after talking with the Jamf Protect devs, I think I've (finally) tracked down the issue. 

In short, if another program (such as BlockBlock) uses Endpoint Security (ES), but doesn't make use of ES caching, due to the way that ES is designed, this then means that ES events (such as process spawns) are then passed to all ES clients ...such as Jamf Protect.

From your sample/stack back trace, we can see Jamf performs expensive analysis events on new process spawns, but then ES caches the process to avoid re-performing that same analysis on subsequent process spawns. This works efficiently as long as all other ES clients (BB, etc etc) are **also** using the ES cache. 

I've just updated BlockBlock to now also use the ES cache - and just checked that in. 
Will release a new build shortly, and then fingers crossed everything is back to good :)

**Comment by rgrove** [comment]
@objective-see It worked! With 2.2.4, BlockBlock no longer causes Jamf Protect to consume excessive CPU. The fork performance test completes just as fast whether BlockBlock is enabled or disabled. Thank you!
