### ISSUE TITLE
BLOCKBLOCK ERROR: install failed

### ISSUE THREAD

**Issue by 0xmachos** [objective-see/BlockBlock#11]
OS: macOS Big Sur Beta (`10.16`/`11.0`) (`20A5323l`) (Dev Beta 3)
BlockBlock: `1.0.2`
This is running in a VM using VMware Fusion Tech Preview 20H2.

When I try to install BlockBlock via the command line I get the following.

```
$ sudo BlockBlock\ Installer.app/Contents/MacOS/BlockBlock\ Installer -install
2020-07-23 21:00:20.976 BlockBlock Installer[2227:44461] Sentry Started -- Version: 3.12.4
INFO : KSCrash.m (339): -[KSCrash sendAllReportsWithCompletion:]: Sending 0 crash reports
No matching processes were found

BLOCKBLOCK ERROR: install failed
```

This error is printed by [Line 35 of `src/main.m`](https://github.com/objective-see/BlockBlock/blob/57ca40fc7fef4f6f1ce63d0523438d6c9c6cfe7e/Installer/Source/main.m#L35): 

```
//install
if(YES != cmdlineInterface(ACTION_INSTALL_FLAG))
    {
       //err msg
       printf("\nBLOCKBLOCK ERROR: install failed\n\n");     
       
       //bail
       goto bail;
    }
```

**Comment by 0xmachos** [comment]
I think this may be related to Big Sur reporting it's version as `11.0` instead of `10.16` but I'm not sure. I was able to install BlockBlock in Big Sur Dev Beta 1 when it was running on bare metal but in a VM on Dev Beta 3, as stated above, I get this error. 

I believe that Big Sur Dev Beta 1 on bare metal was reporting it's version as `10.16` but I can't remember for sure.

**Comment by jguerin** [comment]
Ditto!

**Comment by garrettoreilly** [comment]
I'm seeing this as well.

**Comment by jguerin** [comment]
Confirmed that the Beta build fixes the issue!

**Comment by 0xmachos** [comment]
@objective-see what was the fix? Can you link to a commit?

I've not tested this yet on BS but @jguerin comment sounds good.

**Comment by 0xmachos** [comment]
@jguerin thanks mate, totally missed that.

**Comment by 0xmachos** [comment]
Also confirmed that 1.0.3 BETA works.
