### ISSUE TITLE
BlockBlock is not active popup; Even on uninstall

### ISSUE THREAD

**Issue by cgarrovillo** [objective-see/BlockBlock#15]
Not so sure how to debug this so i'm posting here

BlockBlock shows that it's not active every startup, even after installing and even if it is active. There are no logs that show either in console.app. 

<img width="960" alt="bb" src="https://user-images.githubusercontent.com/6688713/95940850-99b88c80-0d9c-11eb-9a54-87d29b34e12c.png">
<img width="660" alt="bbcon" src="https://user-images.githubusercontent.com/6688713/95940856-9fae6d80-0d9c-11eb-8457-832d22b6b702.png">

**Comment by objective-see** [comment]
Thanks for the bug report!

A few ideas to help resolve this:
1. Can you check if the BlockBlock daemon is running (either via Activity Monitor with View->All Processes checked):
![image](https://user-images.githubusercontent.com/11327812/95943992-e7c09680-0d82-11eb-9dcb-0ee1b5958b6b.png)

Or via the terminal, 
```
$ ps aux | grep -i BlockBlock

root     /Library/Objective-See/BlockBlock/BlockBlock.app/Contents/MacOS/BlockBlock
patrick  /Applications/BlockBlock Helper.app/Contents/MacOS/BlockBlock Helper
```

2. Confirm that the BlockBlock item in System Prefs/Full Disk Access points to `/Library/Objective-See/BlockBlock/BlockBlock.app/` (right click on it, then, "Show In Finder")
![image](https://user-images.githubusercontent.com/11327812/95944108-2bb39b80-0d83-11eb-8987-ccba4ae5beec.png)

...if it does not, manually remove it, then manually add it (click '+' then `/Library/Objective-See/BlockBlock/BlockBlock.app/`)

**Comment by cgarrovillo** [comment]
Okay so it looks like the daemon didn't run at all. 
> `christian         1365   0.0  0.6  9043872  98800   ??  Ss   11:50pm   0:20.56 /Applications/Visual Studio Code.app/Contents/MacOS/Electron /Users/christian/GitHub/BlockBlock
`
> `christian          496   0.0  0.2  4983212  26704   ??  S    11:50pm   0:00.57 /Applications/BlockBlock Helper.app/Contents/MacOS/BlockBlock Helper`

This was taken right after a restart and opening up VSCode. 
What's weird is after many `uninstall -> AppCleaner -> clean shutdown -> install` cycles the FDA in System Preferences would be prefilled with the checkbox ticked already. (disappears on uninstall and reappears instantly ticked on re-install)
After executing the line `pkill -HUP -u root -f tccd` that issue seems to disappear, as I had to manually add the app, but it's still broken.

**Comment by cgarrovillo** [comment]
One more thing I want to add, it looks like my preferences are also not being respected anymore: 
<img width="275" alt="bb" src="https://user-images.githubusercontent.com/6688713/95950549-fd998000-0db1-11eb-88dd-996da748eb86.png">

Not sure if you can deduce anything out of these haha but figured it's a step

**Comment by objective-see** [comment]
No running daemon would result in both the FDA alert and in issue with the preferences.

The daemon is started via 
`/Library/LaunchDaemons/com.objective-see.blockblock.plist`  ...so can you confirm that file exists?

And what happens if you manually start it? 
`sudo launchctl load /Library/LaunchDaemons/com.objective-see.blockblock.plist` 

Issues/errors would be logged (visible in Console.app, filtering on `BlockBlock`)

...a full uninstall/re-install of BB might also fix this?

**Comment by cgarrovillo** [comment]
Solved. the daemon was disabled and forcefully loaded by the `-w` flag.
> `sudo launchctl load -w /Library/LaunchDaemons/com.objective-see.blockblock.plist`

Weird that this persisted throughout restarts, clean install/uninstalls. The man page says the state is _stored elsewhere on disk_. No idea where.

I also think this might've been because I started disabling random stuff using KnockKnock.
