### ISSUE TITLE
BlockBlock stuck at 100% CPU

### ISSUE THREAD

**Issue by jguerin** [objective-see/BlockBlock#16]
BlockBlock beta was stuck at 100% CPU. App and interface was responsive. Disabling and enabling didn't seem to fix it.

[
[Spindump.zip](https://github.com/objective-see/BlockBlock/files/5406488/Spindump.zip)
[Sample of BlockBlock.txt](https://github.com/objective-see/BlockBlock/files/5406489/Sample.of.BlockBlock.txt)

](url)

**Comment by objective-see** [comment]
Can you try version1.1? (https://bitbucket.org/objective-see/deploy/downloads/BlockBlock_1.1.0.zip) 
...should (hopefully) alleviate this issue. Though if it does not, please let me know! Thanks

**Comment by jguerin** [comment]
I'm on 1.1, but only saw this repro once on 1.0.4. Captured what I could in case you saw something in the dumps.

**Comment by jguerin** [comment]
Not reproing any more.
