### ISSUE TITLE
BlockBlock 1.0.4 update check didn't pick up 1.1 update

### ISSUE THREAD

**Issue by jguerin** [objective-see/BlockBlock#17]
Tried to let the 1.0.4 client update itself, but it didn't find a new version. Had to manually update.

**Comment by pwardle** [comment]
I've yet to update the server-side JSON (that contains the new version #)
Wanted to give it a few days, before pushing out the auto-update notification! 

Will update that shortly!

**Comment by jguerin** [comment]
Oops, sorry. I'm used to update servers having staged rollouts :)

**Comment by jguerin** [comment]
Updated correctly later.
