### ISSUE TITLE
BlockBlock Helper will not close with ⌘W or ⌘Q

### ISSUE THREAD

**Issue by tjluoma** [objective-see/BlockBlock#2]
BlockBlock Helper lacks a standard macOS menus:

<img width="730" alt="2020-04-13-06 22 11-BlockBlock-Helper-and-cmd-Q-or-cmd-W" src="https://user-images.githubusercontent.com/26965/79113590-39925080-7d4f-11ea-98a4-0caf34b6c11c.png">

which would be "Acceptable But Still Odd" ***except*** that it also does not close with the standard Command+Q (⌘Q) or Command+W (⌘W).

It appears the only way to close the window is by clicking on the 'x' at the top-left of the window… like some sort of primitive caveman.

**Comment by objective-see** [comment]
Thanks!

Improved dropdown menu and added support for "Close Window" (⌘ + W) 
...'Quit' isn't supported, as we need the client to keep running (albeit in the background, with no windows) to listen for alerts to display. 

![image](https://user-images.githubusercontent.com/11327812/79181987-59eef900-7da9-11ea-86ce-64ba80adecae.png)
