### ISSUE TITLE
Checking https://objective-see.com/products.json for updates

### ISSUE THREAD

**Issue by tjluoma** [objective-see/BlockBlock#26]
BlockBlock Helper checks https://objective-see.com/products.json for updates, but that is super out of date for BlockBlock

```
  "BlockBlock":
  {
    "description": "Provides continual protection by monitoring persistence locations. Any new persistent component will trigger an alert, allowing malicious items be blocked.",
    "version": "0.9.9.4",
    "zip" : "https://bitbucket.org/objective-see/deploy/downloads/BlockBlock_0.9.9.4.zip"
   },
```

**Comment by luckman212** [comment]
@tjluoma Seems it's (silently) been fixed. Thanks @objective-see (if it was you...)

**Comment by tjluoma** [comment]
Ths same JSON file now shows:

```
  "BlockBlock":
  {
    "description": "Provides continual protection by monitoring persistence locations. Any new persistent component will trigger an alert, allowing malicious items be blocked.",
    "version": "2.0.3",
    "zip" : "https://github.com/objective-see/BlockBlock/releases/download/v2.0.3/BlockBlock_2.0.3.zip"
   },
```

so it has been fixed. Closing issue.

**Comment by hmijail** [comment]
Looks like this keeps being a problem - most of my Objective-See utilities turn out to be out of date by months! Pretty disappointing given the context: a self-update that says everything is OK is just false security. Maybe better to remove the self-updating so users know they have to do it manually.

**Comment by hmijail** [comment]
Or, suggestion: in the messages reporting that the current version is the latest, add something like "as of <date of the json file>". At least the user will see that something is clearly outdated.
