### ISSUE TITLE
Helper shows version 0.9.9.9

### ISSUE THREAD

**Issue by tjluoma** [objective-see/BlockBlock#3]
<img width="1002" alt="2020-04-13-06 36 55-BlockBlock-Helper-Wrong-Version-Number" src="https://user-images.githubusercontent.com/26965/79114444-50d23d80-7d51-11ea-8494-44a1390dbab4.png">

The CFBundleShortVersionString and CFBundleVersion version numbers for "/Applications/BlockBlock Helper.app" are both 0.9.9.9

/Library/Objective-See/BlockBlock/BlockBlock.app is 1.0.0.

I assume they are supposed to match and this was just an oversight. Otherwise it's confusing to have one part of the app be a different version number… although I realize they are technically two apps… but they are part of a set… so I still expect the numbers to match. Or maybe just don't put the version number in the Helper title bar so I'm less likely to see it :-)

**Comment by objective-see** [comment]
Ah, this is just so when v1.0.0 is no longer in beta (and that will then be bumped to 1.0.0) beta versions will be able to detect there is a new (final) version - and prompt for an update!
