### ISSUE TITLE
Resize columns in Rules window?

### ISSUE THREAD

**Issue by luckman212** [objective-see/BlockBlock#34]
- BlockBlock 2.0.5
- Monterey 12.1

During what I believe was a background preinstall of Monterey 12.1, a bunch of alerts from BlockBlock popped up.

I wanted to see the full path to the files being reported, but as indicated in the screenshot below, the column dividers are not draggable. 

I see you can widen the entire window, and then click on the items one at a time to reveal their full path, but it would be nice if the entire list could simply be widened to show all content.

![image](https://user-images.githubusercontent.com/1992842/146080650-f52cbef6-9595-45c4-974d-5a297399f4e0.png)

**Comment by objective-see** [comment]
Thanks for the suggestion!
You can now (as of v2.1.2) resize the window,  which will resize (expand) the "Process" column.
