### ISSUE TITLE
BlockBlock Helper contains wrong version number

### ISSUE THREAD

**Issue by suschizu** [objective-see/BlockBlock#37]
the BlockBlock Helper app still contains version 2.1.0 instead of 2.1.1
(the installer is ok - it contains the right version number)

<img width="381" alt="Screenshot 2022-02-24 at 17 29 21" src="https://user-images.githubusercontent.com/16004333/155567184-a9a55773-b15a-4e74-b9fa-b873cb13c78c.png">

**Comment by objective-see** [comment]
Ah, thanks for the bug report!
...now fixed (in v2.1.2)
