### ISSUE TITLE
How to Manually Uninstall 0.9.7

### ISSUE THREAD

**Issue by tjluoma** [objective-see/BlockBlock#4]
I went to uninstall 0.9.7 and found that I cannot. 

I launched the 0.9.7 installer, and "Uninstall" is greyed out.

I tried to re-run the installer, thinking that I could then uninstall it, but the installer failed with "Install Failed".

If I need/want to manually uninstall, is there anything besides this folder: 

`/Library/Objective-See/BlockBlock/`

and this file: 

`$HOME/Library/LaunchAgents/com.objectiveSee.blockblock.plist`

?

**Comment by 0xmachos** [comment]
There's also 
- `/Library/LaunchDaemons/com.objective-see.blockblock.plist`
- `/Applications/BlockBlock Helper.app`

I ran `mdfind blockblock | grep -v '/Users/'` to find them.

**Comment by objective-see** [comment]
The latest installer (v1.0.0) should remove any version of BlockBlock (including betas). 
However if you want to remove it manually, the commands can be found in the [in/uninstaller script](https://github.com/objective-see/BlockBlock/blob/7d1d77e36e5691c0475e00c922ec4a988cac15b3/Installer/Source/Script/configure.sh#L76).

Said commands (for the beta) include:

```
#remove launch agent
launchctl unload "~/Library/LaunchAgents/com.objectiveSee.blockblock.plist"
rm "~/Library/LaunchAgents/com.objectiveSee.blockblock.plist"

#remove launch daemon
launchctl unload "/Library/LaunchDaemons/com.objectiveSee.blockblock.plist"
rm "/Library/LaunchDaemons/com.objectiveSee.blockblock.plist"
```

**Comment by tjluoma** [comment]
> The latest installer (v1.0.0) should remove any version of BlockBlock (including betas).

Yes, but the latest installer will only work on 10.15, and I have multiple Macs which cannot be upgraded to that.

**Comment by objective-see** [comment]
Ah fair point! 
...the manual steps should work, or an older version (such as [v0.9.9.4](https://bitbucket.org/objective-see/deploy/downloads/BlockBlock_0.9.9.4.zip)) may work too!
