### ISSUE TITLE
BlockBlock 2.1.4 says not active

### ISSUE THREAD

**Issue by gru3zi** [objective-see/BlockBlock#42]
Everytime I boot up (Mac mini 2018, macOS Monterey version 12.3.1) I am being told BlockBlock is not active as it does not have full disk access despite seeing clearly in the settings it has full disk access for both BlockBlock and BlockBlockl helper. If i reinstall it, it has disk access and works fully until I reboot and its not working again. 

What could be wrong?

**Comment by luckman212** [comment]
Maybe your TCC.db is messed up. I think I've had this happen before. You might need to boot into recovery mode and nuke it.

see https://recoursive.com/2020/03/03/reset_macos_privacy_permissions/

**Comment by gru3zi** [comment]
I looked around online but could not find much about the tcc.db. Is it safe to delete it completely? Are there any great risks like me not being able to boot my mac? Appreciate your time.

**Comment by luckman212** [comment]
It's safe to delete. The tcc.db is [well known](https://www.rainforestqa.com/blog/macos-tcc-db-deep-dive). The only "risk" is that you will need to re-add any custom permissions you have set in Privacy prefs.

**Comment by gru3zi** [comment]
Seems to have sold the issue. I appreciate your help!
