### ISSUE TITLE
Long process args/path causes window to appear offscreen

### ISSUE THREAD

**Issue by luckman212** [objective-see/BlockBlock#5]
- macOS 10.15.4
- BlockBlock 1.0.0

I was installing a Parallels update yesterday and got an alert from BlockBlock. A portion of the alert was positioned off to the right side of the screen. Picture's worth 1000 words, see below:
![image](https://user-images.githubusercontent.com/1992842/79982331-23357480-8474-11ea-8b58-aa028ec07027.png)

Hopefully a future version can wrap the path/args fields so the window size doesn't expand beyond the screen borders!

**Comment by objective-see** [comment]
should now be fixed in: [version 1.0.1](https://bitbucket.org/objective-see/deploy/downloads/BlockBlock_1.0.1.zip)

**Comment by luckman212** [comment]
@objective-see Beautiful - thank you so much! 🎉
