### ISSUE TITLE
false alerts for /Library/Apple/System/Library/InstallerSandboxes/*

### ISSUE THREAD

**Issue by theevilbit** [objective-see/BlockBlock#51]
Hi Patrick,

I'm getting false alerts for KEXTs for files inside: `/Library/Apple/System/Library/InstallerSandboxes/*`

e.g.: install a KDK, and it will throw a lot of alerts.

Thanks,
Csaba

**Comment by objective-see** [comment]
Thanks for the bug report and appreciate the patience. 
Just [released v2.1.5](https://github.com/objective-see/BlockBlock/releases/tag/v2.1.5) that improves the kext-matching regex to avoid this. 

(More details on fix, here: https://github.com/objective-see/BlockBlock/issues/52#issuecomment-1310879671).

**Comment by objective-see** [comment]
Closing as fixed in v2.1.5 (See: https://github.com/objective-see/BlockBlock/commit/ed7d7b653f609b783a3ac6b482a3845a20da03a6)
