### ISSUE TITLE
macOS 12.6.1 Update on Apple Silicon with BlockBlock v2.1.4 com.apple.MobileSoftwareUpdate.UpdateBrainService

### ISSUE THREAD

**Issue by rudelm** [objective-see/BlockBlock#53]
Hi,

I've just tried to run the Software Update for macOS 12.6.1 update with BlockBlock v2.1.4 running and was greeting by a flood of permission checks for

com.apple.MobileSoftwareUpdate.UpdateBrainService
<img width="1413" alt="macOS1261BlockBlockBerserk" src="https://user-images.githubusercontent.com/1426140/197608343-da74bdca-9166-4114-a66e-0bc947aced69.png">

I've allowed some of them but have disabled BlockBlock for the time being, so that the update process can finish. There's no way to accept all requests of the update. I wonder if the update will succeed with BlockBlock interfering this much.

Is this a known problem? What should be the suggested excemption rule for the UpdateBrainService?

**Comment by rudelm** [comment]
At least the update succeeded. I left all windows open and let the installer run. BlockBlock is now enabled again. I've accepted a few of the UpdateBrainService requests, but would like to clean them up from the rules list. Is there a way I can filter for a given string, so that I can remove all of the entries at once?

<img width="1216" alt="blockBlockUpdateBrainServiceRules" src="https://user-images.githubusercontent.com/1426140/197615646-aedad4de-1ec0-4611-b144-f76bd7145926.png">

**Comment by quartermarsh** [comment]
Same here. I just force quit the helper so I don’t have that many entries to deal with. This was on BlockBlock v2.0.4 so it appears this situation was not dealt with in v2.1.4. Glad to hear the update succeeded at least.

> What should be the suggested excemption rule for the UpdateBrainService?

Inquiring minds want to know!

**Comment by quartermarsh** [comment]
@objective-see Is this related to #38

**Comment by objective-see** [comment]
> @objective-see Is this related to #38?

@quartermarsh, it appears to be related to #52. 
Just [released a v2.1.5](https://github.com/objective-see/BlockBlock/releases/tag/v2.1.5) with a fix 🤞

**Comment by rudelm** [comment]
Thank you @objective-see I've just downloaded and updated manually, since it wasn't detected as an update yet from the app itself. Its still working so far and I'm looking forward to the next macOS update to test it :) But from looking at #52 it seems to be the same issue and if that changed RegEx fixes it, I'm fine with closing this and commenting any follow up problems there if you want?

**Comment by objective-see** [comment]
Thanks @rudelm! 🙏🏽
Yes, same issue as #52 ...closing out both as this now should be fixed! (See: https://github.com/objective-see/BlockBlock/commit/ed7d7b653f609b783a3ac6b482a3845a20da03a6)

(Can re-open if the fix proves to be insufficient)

**Comment by quartermarsh** [comment]
@objective-see 🙏
