### ISSUE TITLE
OS Ventura bug

### ISSUE THREAD

**Issue by tomwaits** [objective-see/BlockBlock#56]
Hello,

Yesterday I upgraded to OS Ventura and now BlockBlock doesn't start.  It doesn't recognize that it has full disk access, even after manual restart.  

Thanks,
Tom

**Comment by prenagha** [comment]
looks like same issue as #54

**Comment by objective-see** [comment]
Yes, please see #54 for more info/workaround. 
(Note: this is an Apple bug - they've promised a fix).

**Comment by objective-see** [comment]
This has now been fixed by Apple in macOS Ventura 13.0.1 🙌🏽
