### ISSUE TITLE
BlockBlock Helper (1.0.1) stays in the dock after alert is dismissed.

### ISSUE THREAD

**Issue by tjluoma** [objective-see/BlockBlock#6]
Just upgraded to version 1.0.1

It seems like every time BlockBlock puts up an alert, the **BlockBlock Helper.app** icon appears in the dock, and it does not go away, even when the BlockBlock alert is dismissed.

I can make it go away by clicking on the dock icon and quitting it, but that gets tedious quick. Or maybe I'm just ill-tempered and this is a message from God telling me to be more patient in life. But unless you're sure about that, I think it might be a bug.

**Comment by objective-see** [comment]
ah, good catch! 
Tracked down the issue and just checked in fix, will release new version shortly :)

**Comment by objective-see** [comment]
[v1.0.2 is now out](https://bitbucket.org/objective-see/deploy/downloads/BlockBlock_1.0.2.zip) (though you may have to manually update)
...contains fix for this issues!
