### ISSUE TITLE
Figma adds a login item undetected

### ISSUE THREAD

**Issue by mernen** [objective-see/BlockBlock#64]
Every time [Figma](https://www.figma.com/downloads/) gets an update, it adds itself to the login items:

<img width="370" alt="Screenshot 2023-07-20 at 15 42 01" src="https://github.com/objective-see/BlockBlock/assets/6412/76a7213c-8331-4a27-937d-ceeaee0e05a8">

Sadly, BlockBlock doesn't notice anything. As there's no option to disable this behavior in Figma, so I was hoping BlockBlock would help me.

**Comment by mernen** [comment]
I hadn't seen issue #57, but I'm guessing it's possibly related?

**Comment by objective-see** [comment]
Yes, same as #57 :) 
Fixed in v2.2.0

**Comment by mernen** [comment]
Thanks! Working perfectly.

**Comment by mernen** [comment]
Spoke too soon. :( The last two Figma updates successfully bypassed BlockBlock. Also, when I open BlockBlock Helper, it says there are no rules (i.e. the occasion it successfully blocked Figma two weeks ago somehow didn't persist the rule).
