### ISSUE TITLE
Low-resolution menu bar icon

### ISSUE THREAD

**Issue by ehamberg** [objective-see/BlockBlock#8]
The menu bar icon seems to be a low-resolution image:

<img width="103" alt="Screenshot 2020-04-28 at 08 33 14" src="https://user-images.githubusercontent.com/16063/80454966-3096a700-892b-11ea-9045-2861a8f5e205.png">

**Comment by jguerin** [comment]
Would love to see a high-resolution icon added too :) BlockBlock is the only one with a fuzzy icon in my menu bar

**Comment by objective-see** [comment]
(re)created status bar icon:
![image](https://user-images.githubusercontent.com/11327812/96532932-9acc3c80-1228-11eb-95ef-70343ff3117b.png)

...hopefully no longer blurry/low-resolution!

**Comment by ehamberg** [comment]
Looks great in version 1.1. I could finally enable the icon again. Thanks! 😄

**Comment by jguerin** [comment]
Looks great!
