### ISSUE TITLE
Reason release not updated to 2.2.4 on website?

### ISSUE THREAD

**Issue by RielDowner** [objective-see/BlockBlock#80]
Hiya,

With the performance improvements offered by 2.2.3 & 2.2.4 I was wondering if there was a reason that 2.2.4 wasn't the release linked to on the site (which is still 2.2.2)...

Is 2.2.4 'safe' to use? Or is it a beta / 'unstable' release?

**Comment by objective-see** [comment]
Thanks for the ping! 
v2.2.4 is yes, safe to use/is the latest stable version. 

I've just updated the webpage to reflect this as the latest version!
